apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab07
  labels:
    app: frontend-lab07
spec:
  selector:
    matchLabels:
      app: frontend-lab07
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab07
    spec:
      containers:
        - name: frontend-lab07
          image: gomdolma/frontend-lab07
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
